MCU ?= atmega32u2
VENDOR_ID ?= 0x481
PRODUCT_ID ?= 0x0002
MANUFACTURER ?= "Model F Labs"
DEBOUNCE_TYPE = sym_eager_pr

ISO_LAYOUT ?= 1
SPLIT_BACKSPACE ?= 0
SPLIT_RIGHT_SHIFT ?= 1

include qmk_core/qmk_port.mk
include xwhatsit_core/xwhatsit_port.mk

DEVICE_OBJS = modelf.o qmk_main.o matrix.o keymap.o matrix_common.o timer.o bitwise.o bootloader.o $(DEBOUNCE_TYPE).o util_comm.o
DEVICE_FLAGS += -DBOOTLOADER_DFU=1 -DBOOTLOADER_ATMEL_DFU=1 -DENABLE_DFU_INTERFACE=1 -DBOOTLOADER_SIZE=4096
DEVICE_FLAGS += -DGENERIC_HID_REPORT_SIZE=32 -DGENERIC_HID_FEATURE_SIZE=16 -DGENERIC_HID_USAGE_PAGE=0xFF60U -DGENERIC_HID_USAGE=0x61 -DGENERIC_HID_INPUT_USAGE=0x62 -DGENERIC_HID_OUTPUT_USAGE=0x63 -DGENERIC_HID_HANDLE_SYNCHRONOUSLY=1 -DISO_LAYOUT=$(ISO_LAYOUT) -DSPLIT_BACKSPACE=$(SPLIT_BACKSPACE) -DSPLIT_RIGHT_SHIFT=$(SPLIT_RIGHT_SHIFT)

COMMON_HEADERS += post_config.h

CONFIG_FLAGS ?= \
	-DUSB_VENDOR_ID=$(VENDOR_ID) \
	-DUSB_PRODUCT_ID=$(PRODUCT_ID) \
	-DMANUFACTURER_STRING='$(MANUFACTURER)' \
	-DPRODUCT_STRING='$(PRODUCT)'
	-DDEBOUNCE=$(DEBOUNCE)

$(BUILDDIR)/modelf.o: led.h generic_hid.h
$(BUILDDIR)/keymap.o: keymap.h config.h usb_keys.h wcass.h
