#ifndef KK_ERGODOX_KEYMAP_H
#define KK_ERGODOX_KEYMAP_H

#include "keycodes.h"
#include "keymap.h"

#define USB_KEY_ERGODOX_LEFT_BACKSPACE  USB_KEY_CAPS_LOCK
#define USB_KEY_ERGODOX_HYPER           USB_KEY_VIRTUAL_APPLE_FN
#define USB_KEY_ERGODOX_MEH             USB_KEY_INSERT
#define USB_KEY_ERGODOX_ALT_QUOTE       USB_KEY_INT_NEXT_TO_LEFT_SHIFT
#define USB_KEY_ERGODOX_RIGHT_LAYER     USB_KEY_SCROLL_LOCK
#define USB_KEY_ERGODOX_LEFT_BIG_LAYER  USB_KEY_LEFT_CTRL
#define USB_KEY_ERGODOX_RIGHT_BIG_LAYER USB_KEY_RIGHT_CTRL
#define USB_KEY_ERGODOX_TOP_LEFT_ARROW  USB_KEY_F1
#define USB_KEY_ERGODOX_TOP_RIGHT_ARROW USB_KEY_F5
#define USB_KEY_ERGODOX_ALT_APPS        USB_KEY_MENU
#define USB_KEY_ERGODOX_ALT_SHIFT       USB_KEY_LEFT_ALT
#define USB_KEY_ERGODOX_GRAVE_LAYER     USB_KEY_BACKTICK
#define USB_KEY_ERGODOX_LEFT_DELETE     USB_KEY_TAB
#define USB_KEY_ERGODOX_RIGHT_TAB       USB_KEY_DELETE

#endif
